import javax.wukong.wkpf.*;
import javax.wukong.virtualwuclasses.*;

public class WKDeploy {

    // =========== Begin: Generated by the translator from application WuML
    /* Component names to indexes:
    {%- for component in changesets.components %}
    {{ component.type }} => {{ component.index }}
    {%- endfor %}
    */

    private final static Object[] heartbeatToNodeAddrMap = {
      {%- for heartbeatgroup in changesets.heartbeatgroups %}
      new byte[]{ {%- for node in heartbeatgroup.nodes %}
        {{ node|nodeinjava }}{{ ',' if not loop.last else '' }}
        {%- endfor %}
      },
      {%- endfor %}
    };

    private final static int[] heartbeatGroupPeriods = {
      {%- for heartbeatgroup in changesets.heartbeatgroups %}
      {{ heartbeatgroup.period }},
      {%- endfor %}
    };
    // =========== End: Generated by the translator from application WuML

    public static void main (String[] args) {
        // System.out.println("{{ name }}");
        System.out.println("My node id: " + WKPF.getMyNodeId());
        // WKPF.loadHeartbeatToNodeAddrMap(heartbeatToNodeAddrMap);
        // WKPF.loadHeartbeatPeriods(heartbeatGroupPeriods);
        initialiseLocalWuObjects();

        while(true){
            VirtualWuObject wuobject = WKPF.select();
            if (wuobject != null) {
                wuobject.update();
            }
        }
    }

    private static void initialiseLocalWuObjects() {
        {%- for component in changesets.components %}
        //all WuClasses from the same group has the same instanceIndex and wuclass
        if (WKPF.isLocalComponent((short){{ component.index }})) {

            {% for wuobject in component.instances %}

            if (WKPF.getMyNodeId() == (short){{ wuobject.node_id }}) {
                {% if not wuobject.hasLocalWuClass %}

                // Virtual WuClasses (Java)
                VirtualWuObject wuclassInstance{{ wuobject.wuclass|wuclassname }} = new {{ wuobject.wuclass|wuclassvirtualclassname }}();
                WKPF.registerWuClass(GENERATEDWKPF.{{ wuobject.wuclass|wuclassconstname }}, {{ wuobject.wuclass|wuclassgenclassname }}.properties);
                WKPF.createWuObject((short)GENERATEDWKPF.{{ wuobject.wuclass|wuclassconstname }}, WKPF.getPortNumberForComponent((short){{ component.index }}), wuclassInstance{{ wuobject.wuclass|wuclassname }});
                {%- for property in wuobject.wuclass.properties -%}
                {%- if property.value -%}
                {% if property.datatype.lower() == 'boolean' %}
                WKPF.setPropertyBoolean(wuclassInstance{{ wuobject.wuclass|wuclassname }}, GENERATEDWKPF.{{ property|propertyconstname }}, {{ property.value }});
                {% elif property.datatype.lower() == 'int' or property.datatype.lower() == 'short' %}
                WKPF.setPropertyShort(wuclassInstance{{ wuobject.wuclass|wuclassname }}, GENERATEDWKPF.{{ property|propertyconstname }}, (short){{ property.value }});
                {% elif property.datatype.lower() == 'refresh_rate' %}
                WKPF.setPropertyRefreshRate(wuclassInstance{{ wuobject.wuclass|wuclassname }}, GENERATEDWKPF.{{ property|propertyconstname }}, (short){{ property.value }});
                {% else %}
                WKPF.setPropertyShort(wuclassInstance{{ wuobject.wuclass|wuclassname }}, GENERATEDWKPF.{{ property|propertyconstname }}, GENERATEDWKPF.{{ property|propertyconstantvalue }});
                {%- endif -%}
                {%- endif -%}
                {%- endfor -%}

                {% else %}

                // Native WuClasses (C)
                WKPF.createWuObject((short)GENERATEDWKPF.{{ wuobject.wuclass|wuclassconstname }}, WKPF.getPortNumberForComponent((short){{ component.index }}), null);
                {%- for property in wuobject.wuclass.properties -%}
                {%- if property.value -%}
                {% if property.datatype.lower() == 'boolean' %}
                WKPF.setPropertyBoolean((short){{ component.index }}, GENERATEDWKPF.{{ property|propertyconstname }}, {{ property.value }});
                {% elif property.datatype.lower() == 'int' or property.datatype.lower() == 'short' %}
                WKPF.setPropertyShort((short){{ component.index }}, GENERATEDWKPF.{{ property|propertyconstname }}, (short){{ property.value }});
                {% elif property.datatype.lower() == 'refresh_rate' %}
                WKPF.setPropertyRefreshRate((short){{ component.index }}, GENERATEDWKPF.{{ property|propertyconstname }}, (short){{ property.value }});
                {% else %}
                WKPF.setPropertyShort((short){{ component.index }}, GENERATEDWKPF.{{ property|propertyconstname }}, GENERATEDWKPF.{{ property|propertyconstantvalue }});
                {%- endif -%}
                {%- endif -%}
                {%- endfor -%}

                {% endif %}

            }

            {% endfor %}

        }

        {%- endfor %}
    }
}
