import javax.wukong.wkpf.*;
import javax.wukong.virtualwuclasses.*;

public class LightDemo {

    // =========== Begin: Generated by the translator from application WuML
    /* Component instance IDs to indexes:
    Light_Sensor => 0
    Threshold => 1
    Numeric_Controller => 2
    Onboard_Light_Actuator => 3
    */

    //link table
    // fromInstanceIndex(2 bytes), fromPropertyId(1 byte), toInstanceIndex(2 bytes), toPropertyId(1 byte), toWuClassId(2 bytes)
    //eg. (byte)0,(byte)0, (byte)0, (byte)2,(byte)0, (byte)1, (byte)1,(byte)0
    private final static byte[] linkDefinitions = {
        // Note: Component instance id and wuclass id are little endian
        // Note: using WKPF constants now, but this should be generated as literal bytes by the WuML->Java compiler.
        // Connect input controller to threshold
        (byte)0, (byte)0, (byte)0, (byte)1, (byte)0, (byte)2, (byte)1, (byte)0,
        (byte)1, (byte)0, (byte)3, (byte)3, (byte)0, (byte)0, (byte)4, (byte)0,
        (byte)2, (byte)0, (byte)0, (byte)1, (byte)0, (byte)1, (byte)1, (byte)0
    };

    //component node id and port number table
    // each row corresponds to the component index mapped from component ID above
    // each row has two items: node id, port number
    private final static Object[] componentInstanceToWuObjectAddrMap = {
      new byte[]{
        2, 3
      },
      new byte[]{
        2, 4
      },
      new byte[]{
        2, 1
      },
      new byte[]{
        1, 2
      },
    };

    private final static Object[] heartbeatToNodeAddrMap = {
      new byte[]{
        1
      },
    };

    private final static int[] heartbeatGroupPeriods = {
      500,
    };
    // =========== End: Generated by the translator from application WuML

    public static void main (String[] args) {
        System.out.println("WKPFLightDemo");
        System.out.println("" + WKPF.getMyNodeId());
        // WKPF.loadHeartbeatToNodeAddrMap(heartbeatToNodeAddrMap);
        // WKPF.loadHeartbeatPeriods(heartbeatGroupPeriods);
        WKPF.loadComponentToWuObjectAddrMap(componentInstanceToWuObjectAddrMap);
        WKPF.loadLinkDefinitions(linkDefinitions);
        initialiseLocalWuObjects();

        while(true){
            VirtualWuObject wuobject = WKPF.select();
            if (wuobject != null) {
                wuobject.update();
            }
        }
    }

    private static void initialiseLocalWuObjects() {
        //all WuClasses from the same group has the same instanceIndex and wuclass
        if (WKPF.isLocalComponent((short)0)) {

        // Native WuClasses (C)
        WKPF.createWuObject((short)GENERATEDWKPF.WUCLASS_LIGHT_SENSOR, WKPF.getPortNumberForComponent((short)0), null);
        WKPF.setPropertyRefreshRate((short)0, GENERATEDWKPF.PROPERTY_LIGHT_SENSOR_REFRESH_RATE, (short)250);
        
        }
        //all WuClasses from the same group has the same instanceIndex and wuclass
        if (WKPF.isLocalComponent((short)1)) {

        // Native WuClasses (C)
        WKPF.createWuObject((short)GENERATEDWKPF.WUCLASS_THRESHOLD, WKPF.getPortNumberForComponent((short)1), null);
        WKPF.setPropertyShort((short)1, GENERATEDWKPF.PROPERTY_THRESHOLD_OPERATOR, GENERATEDWKPF.ENUM_THRESHOLD_OPERATOR_LT);
        WKPF.setPropertyShort((short)1, GENERATEDWKPF.PROPERTY_THRESHOLD_THRESHOLD, (short)30);
        
        WKPF.setPropertyShort((short)1, GENERATEDWKPF.PROPERTY_THRESHOLD_VALUE, (short)20);
        
        WKPF.setPropertyBoolean((short)1, GENERATEDWKPF.PROPERTY_THRESHOLD_OUTPUT, false);
        
        }
        //all WuClasses from the same group has the same instanceIndex and wuclass
        if (WKPF.isLocalComponent((short)2)) {

        // Native WuClasses (C)
        WKPF.createWuObject((short)GENERATEDWKPF.WUCLASS_NUMERIC_CONTROLLER, WKPF.getPortNumberForComponent((short)2), null);
        WKPF.setPropertyShort((short)2, GENERATEDWKPF.PROPERTY_NUMERIC_CONTROLLER_OUTPUT, (short)200);
        
        }
        //all WuClasses from the same group has the same instanceIndex and wuclass
        if (WKPF.isLocalComponent((short)3)) {

        // Native WuClasses (C)
        WKPF.createWuObject((short)GENERATEDWKPF.WUCLASS_LIGHT_ACTUATOR, WKPF.getPortNumberForComponent((short)3), null);
        WKPF.setPropertyBoolean((short)3, GENERATEDWKPF.PROPERTY_LIGHT_ACTUATOR_ON_OFF, false);
        
        }
    }
}
